apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate-staging-examplesubdomain
  namespace: examplesubdomain
spec:
  # commonName: *.examplesubdomain.hpi-schul-cloud.dev
  dnsNames:
  - '*.examplesubdomain.hpi-schul-cloud.dev'
  - '*.dev.examplesubdomain.hpi-schul-cloud.dev'
  issuerRef:
    kind: ClusterIssuer
    name: sc-cert-manager-clusterissuer-letsencrypt-staging-otcdns
  secretName: wildcard-certificate-staging-examplesubdomain-tls
