name: Publish Docker image
on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  push:
    tags:
      - 'v*'  
  workflow_dispatch:
        
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - # https://github.com/docker/metadata-action
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            schulcloud/infra-otc-cert-manager-webhook
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha        
            type=semver,pattern={{version}}
      - # https://github.com/docker/login-action
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - # https://github.com/docker/build-push-action
        name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: schulcloud/infra-otc-cert-manager-webhook:latest,${{ steps.meta.outputs.tags }}
